-- HUMSSGrade11FirstSemester Table
CREATE TABLE HUMSSGrade11FirstSemester (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    MiddleName NVARCHAR(50) NULL,
    LastName NVARCHAR(50) NOT NULL,
    SuffixName NVARCHAR(20) NULL,
    Gender NVARCHAR(20) NOT NULL,
    Status NVARCHAR(20) NOT NULL,
    Citizenship NVARCHAR(50) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Birthplace NVARCHAR(100) NOT NULL,
    StreetNumber NVARCHAR(20) NULL,
    Street NVARCHAR(100) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Province NVARCHAR(100) NOT NULL,
    ZipCode NVARCHAR(10) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    MobileNumber NVARCHAR(15) NOT NULL,
    BirthCertificatePath NVARCHAR(255) NULL,
    ReportCardPath NVARCHAR(255) NULL,
    GoodMoralCharacterPath NVARCHAR(255) NULL,
    IDPicturePath NVARCHAR(255) NULL,
    Form137Path NVARCHAR(255) NULL,
    Form138Path NVARCHAR(255) NULL,
    AccountFirstName NVARCHAR(50) NULL,
    AccountLastName NVARCHAR(50) NULL,
    AccountEmail NVARCHAR(100) NULL,
    AccountMobile NVARCHAR(15) NULL,
    AccountPassword NVARCHAR(255) NULL,
    GuardianName NVARCHAR(100) NULL,
    GuardianEmail NVARCHAR(100) NULL,
    GuardianMobileNumber NVARCHAR(15) NULL,
    GuardianTelephoneNumber NVARCHAR(15) NULL,
    GuardianOccupation NVARCHAR(50) NULL,
    GuardianCompany NVARCHAR(50) NULL,
    GuardianRelationship NVARCHAR(50) NULL,
    EnrollmentDate DATETIME DEFAULT GETDATE()
);

-- HUMSSGrade11FirstSemester Table
CREATE TABLE HUMSSGrade11SecondSemester (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    MiddleName NVARCHAR(50) NULL,
    LastName NVARCHAR(50) NOT NULL,
    SuffixName NVARCHAR(20) NULL,
    Gender NVARCHAR(20) NOT NULL,
    Status NVARCHAR(20) NOT NULL,
    Citizenship NVARCHAR(50) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Birthplace NVARCHAR(100) NOT NULL,
    StreetNumber NVARCHAR(20) NULL,
    Street NVARCHAR(100) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Province NVARCHAR(100) NOT NULL,
    ZipCode NVARCHAR(10) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    MobileNumber NVARCHAR(15) NOT NULL,
    BirthCertificatePath NVARCHAR(255) NULL,
    ReportCardPath NVARCHAR(255) NULL,
    GoodMoralCharacterPath NVARCHAR(255) NULL,
    IDPicturePath NVARCHAR(255) NULL,
    Form137Path NVARCHAR(255) NULL,
    Form138Path NVARCHAR(255) NULL,
    AccountFirstName NVARCHAR(50) NULL,
    AccountLastName NVARCHAR(50) NULL,
    AccountEmail NVARCHAR(100) NULL,
    AccountMobile NVARCHAR(15) NULL,
    AccountPassword NVARCHAR(255) NULL,
    GuardianName NVARCHAR(100) NULL,
    GuardianEmail NVARCHAR(100) NULL,
    GuardianMobileNumber NVARCHAR(15) NULL,
    GuardianTelephoneNumber NVARCHAR(15) NULL,
    GuardianOccupation NVARCHAR(50) NULL,
    GuardianCompany NVARCHAR(50) NULL,
    GuardianRelationship NVARCHAR(50) NULL,
    EnrollmentDate DATETIME DEFAULT GETDATE()
);

-- HUMSSGrade11FirstSemester Table
CREATE TABLE HUMSSGrade12FirstSemester (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    MiddleName NVARCHAR(50) NULL,
    LastName NVARCHAR(50) NOT NULL,
    SuffixName NVARCHAR(20) NULL,
    Gender NVARCHAR(20) NOT NULL,
    Status NVARCHAR(20) NOT NULL,
    Citizenship NVARCHAR(50) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Birthplace NVARCHAR(100) NOT NULL,
    StreetNumber NVARCHAR(20) NULL,
    Street NVARCHAR(100) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Province NVARCHAR(100) NOT NULL,
    ZipCode NVARCHAR(10) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    MobileNumber NVARCHAR(15) NOT NULL,
    BirthCertificatePath NVARCHAR(255) NULL,
    ReportCardPath NVARCHAR(255) NULL,
    GoodMoralCharacterPath NVARCHAR(255) NULL,
    IDPicturePath NVARCHAR(255) NULL,
    Form137Path NVARCHAR(255) NULL,
    Form138Path NVARCHAR(255) NULL,
    AccountFirstName NVARCHAR(50) NULL,
    AccountLastName NVARCHAR(50) NULL,
    AccountEmail NVARCHAR(100) NULL,
    AccountMobile NVARCHAR(15) NULL,
    AccountPassword NVARCHAR(255) NULL,
    GuardianName NVARCHAR(100) NULL,
    GuardianEmail NVARCHAR(100) NULL,
    GuardianMobileNumber NVARCHAR(15) NULL,
    GuardianTelephoneNumber NVARCHAR(15) NULL,
    GuardianOccupation NVARCHAR(50) NULL,
    GuardianCompany NVARCHAR(50) NULL,
    GuardianRelationship NVARCHAR(50) NULL,
    EnrollmentDate DATETIME DEFAULT GETDATE()
);

-- HUMSSGrade11FirstSemester Table
CREATE TABLE HUMSSGrade12SecondSemester (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    MiddleName NVARCHAR(50) NULL,
    LastName NVARCHAR(50) NOT NULL,
    SuffixName NVARCHAR(20) NULL,
    Gender NVARCHAR(20) NOT NULL,
    Status NVARCHAR(20) NOT NULL,
    Citizenship NVARCHAR(50) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Birthplace NVARCHAR(100) NOT NULL,
    StreetNumber NVARCHAR(20) NULL,
    Street NVARCHAR(100) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Province NVARCHAR(100) NOT NULL,
    ZipCode NVARCHAR(10) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    MobileNumber NVARCHAR(15) NOT NULL,
    BirthCertificatePath NVARCHAR(255) NULL,
    ReportCardPath NVARCHAR(255) NULL,
    GoodMoralCharacterPath NVARCHAR(255) NULL,
    IDPicturePath NVARCHAR(255) NULL,
    Form137Path NVARCHAR(255) NULL,
    Form138Path NVARCHAR(255) NULL,
    AccountFirstName NVARCHAR(50) NULL,
    AccountLastName NVARCHAR(50) NULL,
    AccountEmail NVARCHAR(100) NULL,
    AccountMobile NVARCHAR(15) NULL,
    AccountPassword NVARCHAR(255) NULL,
    GuardianName NVARCHAR(100) NULL,
    GuardianEmail NVARCHAR(100) NULL,
    GuardianMobileNumber NVARCHAR(15) NULL,
    GuardianTelephoneNumber NVARCHAR(15) NULL,
    GuardianOccupation NVARCHAR(50) NULL,
    GuardianCompany NVARCHAR(50) NULL,
    GuardianRelationship NVARCHAR(50) NULL,
    EnrollmentDate DATETIME DEFAULT GETDATE()
);

